version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /tmp/dados:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=guest1
      - RABBITMQ_DEFAULT_PASS=guest1
      
  mysql-db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alurafood-pagamento
    ports:
      - "3306:3306"
    volumes:
      - "/tmp/data_docker/mysql:/var/lib/mysql"
    cap_add:
      - SYS_NICE  # Desabilitar o aviso "mbind: Operation not permitted"
  adminer:
    image: adminer:4
    container_name: adminer_container
    restart: always
    ports:
      - 8087:8080
      
  

